apm-server:
  host: apm-server:8200

output:
  elasticsearch:
    hosts: elasticsearch:9200

# apm-server.frontend.enabled: true
# apm-server.host: "0.0.0.0:8200"

# output.elasticsearch:
#   hosts: ['elasticsearch:9200']

# setup.kibana:
#   host: "http://kibana:5601"